version: '3'
services:
  redis:
    image: redis:5-alpine
    expose:
      - 6379
  app:
    build: /root/WEB/WEBUIWorkerManagement/backapi
    volumes:
      - .:/usr/src/app/
      - dependencies:/usr/src/app/node_modules
    working_dir: /usr/src/app
    depends_on:
      - redis
    environment:
      DD_AGENT_HOST=datadog-agent
    ports:
      - 3000:3000
    command: node server.js
volumes:
  dependencies:
